### ISSUE TITLE
小矛运第一次自动执行提示任务未完成，手动执行又可以成功

### ISSUE THREAD

**Issue by wyq0201** [yize8888/maotai#27]
**青龙每天第一次自动执行：**
i茅台申购+小茅运
-------------------总共1个用户-------------------
第1个用户----------------王_159**6654开始任务----------------
10941_贵州茅台酒（甲辰龙年）---------------申购完成，请于1月12日18:00查看预约申购结果
2478_贵州茅台酒（珍品）---------------申购完成，请于1月12日18:00查看预约申购结果
10942_贵州茅台酒（甲辰龙年）x2---------------申购完成，请于1月12日18:00查看预约申购结果
王_159**6654---------------小茅运:任务未完成，无法领取奖励
王_159**6654正常结束任务

**再次手动执行又没有问题：**
i茅台申购+小茅运
-------------------总共1个用户-------------------
第1个用户----------------王_159**6654开始任务----------------
10941_贵州茅台酒（甲辰龙年）---------------申购失败:今天已申购，请明日再来
2478_贵州茅台酒（珍品）---------------申购失败:今天已申购，请明日再来
10942_贵州茅台酒（甲辰龙年）x2---------------申购失败:今天已申购，请明日再来
王_159**6654---------------小茅运:领取奖励成功
王_159**6654正常结束任务

请问这个是怎么回事？

**Comment by wyq0201** [comment]
现在 第二次手动执行也不行了，失败的概率很高

**Comment by sanmuhub** [comment]
我直接取消小茅运领取，小茅运领取有个间隔吧
