### ISSUE TITLE
请问imaotai的token在哪里获取呢？

### ISSUE THREAD

**Issue by wspzf** [yize8888/maotai#3]
我对程序抓包后填的cookie好像不对，提示token失效，请重新登录

**Comment by yize8888** [comment]
抓i茅台APP的登录接口，会返回token，如果还不会可以进群交流

**Comment by wspzf** [comment]
> 抓i茅台APP的登录接口，会返回token，如果还不会可以进群交流

要注销抓重新登录的过程才有token吗？我在TG群里问了，还没有解决。
